### ISSUE TITLE
Tensorflow dependencies ?

### ISSUE THREAD

**Issue by boxerab** [RidgeRun/r2inference#35]
I've built this with tensorflow backend. Do I need to pip install tensorflow to get this working ?

**Comment by josejich** [comment]
Hi @boxerab , you don't need to install the python tensorflow API to get r2inference working. Just the C/C++ API, please check our installation wikipage 

https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Supported_backends/TensorFlow#Installation

We do recommend using the tensorflow python API in order to generate models.  Let me know if you run into any issues.

**Comment by carlos-aguero** [comment]
Hi @boxerab, 

Additional to @josejich answer:


Tensorflow at python is required if you are trying to generate models, for example at this wiki:
[Generating Models](https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Supported_backends/TensorFlow#Saving_a_session_with_TensorFlow_python_API)

But we already provide models that can be used with R2I, models are available at our store for free:
[RidgeRun Store Models and Binaries](https://www.ridgerun.com/store/Deep-Learning-Models-and-Binaries-c33344794)

Regards.

**Comment by boxerab** [comment]
Thanks, guys. I just remembered I had already installed the C++ api, so that's why it built.
As for models, if I want to just take a model from the Tensorflow zoo and use it, how can I do that ? Or if I train my own model.

**Comment by boxerab** [comment]
oh, never mind :) I see you have instructions for this.
